server:
  port: 8888

spring:
  application:
    name: configuration-service
  config:
    import: ""

  cloud:
    discovery:
      enabled: true
    config:
      enabled: false
      server:
        git:
          uri: https://github.com/NdiayeGorgui/rent-hub-config-server
          clone-on-start: true
          default-label: main

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always