name: Build and Push AI Service

on:
  push:
    branches:
      - main
    paths:
      - 'ai-service/**'
  pull_request:
    paths:
      - 'ai-service/**'

jobs:
  build-and-push-ai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push AI Service
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/ai-service:latest"

          echo "🔹 Build de ai-service"
          docker build -t $IMAGE_NAME -f ai-service/Dockerfile ai-service
          #                           ^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^
          #                           chemin du Dockerfile      contexte

          echo "📤 Push de $IMAGE_NAME"
          docker push $IMAGE_NAME

          echo "✅ ai-service pushed successfully"